VERTICAL_TILE_NUM = 12
HORIZONTAL_TILE_NUM = 14
TILE_SIZE = 16

screenHeight = VERTICAL_TILE_NUM * TILE_SIZE
screenWidth = HORIZONTAL_TILE_NUM * TILE_SIZE

WORLD_TILE_WIDTH = 68
WORLD_TILE_HEIGHT = 42
worldWidth = WORLD_TILE_WIDTH * TILE_SIZE
worldHeight = WORLD_TILE_HEIGHT * TILE_SIZE